# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jballang <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/09/14 09:55:43 by jballang          #+#    #+#              #
#    Updated: 2016/09/14 10:25:37 by jballang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FILES = ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(FILES)

clean:
	rm -f $(NAME)

re: clean all
